= Engineering Generalizable Features for Eye-Tracking Data Through a Cloud Based Machine Learning Platform
:toc:

== Introduction

=== Cognitive Workload

=== Feature Generalizability

In general machine learning problems you are optimizing a value

Generalizability is especially useful in situations where data is easily available, but labels are not. When



In machine learning problems where there is limited access to data, transfer learning is a popular approach. "Transfer learning and domain adaptation refer to the situation where what has been learned in one setting … is exploited to improve generalization in another setting". Transfer Learning

"Feature generalizability we define as the extent to which extracted features can predict the same variable in different context." [0] As in Sharma et al, the variable we are predicting in multiple contexts is Cognitive Performance, with features engineered from eye-tracking data.

== Related Work

=== Eye Tracking

=== EEG

=== Generalizability

== Datasets

=== EMIP

=== Jetris

== Implementation

Our goal with this system is to create a platform on which we can perform our feature generalizability experiments efficiently and consistently.

The system must also allow for full reproducibility of any experiments ran.

Problems that we want to solve:

* Cloud. We want to be able to run the system in the cloud. So that we can run multiple experiments in parallel and not be limited by our own devices.
* Handle multiple datasets
* Feature set as hyperparameters
* Reproducibility
* Multiple different feature types (heatmap/ts)
* Creating features

=== Cloud
Our cloud provider for this project is google cloud provider.



=== Reproducability
Our reproducibility strategy primarily consists of two different components.
The version-control tool, git; and the machine learning management tool comet.ml.

==== Git
Git keeps track of all versions of our source-code.
We have set up our system to demand that all local changes to the code be committed to git before a run in the cloud will be allowed.
We ensure that all our parameters are represented in the code. This ensures that we always know the state of the code responsible for each experiment.
When we run an experiment in the cloud we log the start parameters of the system and the hash associated with the commit.

==== comet.ml
comet.ml is a machine learning management tool. It can handle user-management, visualization, tracking of experiments, and much more.
In our case we use it to track the results of our experiements, and how they relate to eachother.



One of the primary complications is our need for the combination of different datasets.


== Analysis

=== Cross-Sudy Data Collection

=== Data Pre-Processing

=== Feature Extraction

=== Dimensinality Reduction

=== Prediction: Ensamble Learning

=== Training, validation and testing setup

=== Feature Generalizability Index

=== Bench-marking the Generalizable Features

== Results and Discussion

=== Selecting Generalizable Features

=== Enineering Generalizable Eye-Tracking Features

=== Enineering Generalizable EEG Features

=== On Feature Generalizablity

=== Bench-Mark Results for Generalizable Features

=== Context-Specific Features

=== Implications

=== Limitations

== Conclusion and Further Work
