= Engineering Generalizable Features for Eye-Tracking Data Through a Cloud Based Machine Learning Platform 
:toc:

== Introduction

=== Cognitive Workload

=== Feature Generalizability

In general machine learning problems you are optimizing a value

Generalizability is especially useful in situations where data is easily available, but labels are not. When



In machine learning problems where there is limited access to data, transfer learning is a popular approach. "Transfer learning and domain adaptation refer to the situation where what has been learned in one setting … is exploited to improve generalization in another setting". Transfer Learning

"Feature generalizability we define as the extent to which extracted features can predict the same variable in different context." [0] As in Sharma et al, the variable we are predicting in multiple contexts is Cognitive Performance, with features engineered from eye-tracking data.

== Related Work

=== Eye Tracking

=== EEG

=== Generalizability

== Datasets

=== EMIP

=== Jetris

== Implementation

== Analysis

=== Cross-Sudy Data Collection

=== Data Pre-Processing

=== Feature Extraction

=== Dimensinality Reduction

=== Prediction: Ensumle Learning

=== Training, validation and testing setup

=== Feature Generalizability Index

=== Bench-marking the Generalizable Features

== Results and Discussion

=== Selecting Generalizable Features

=== Enineering Generalizable Eye-Tracking Features

=== Enineering Generalizable EEG Features

=== On Feature Generalizablity

=== Bench-Mark Results for Generalizable Features

=== Context-Specific Features

=== Implications

=== Limitations

== Conclusion and Further Work
